-- Assiny preparation only: no vendor fields, sale statuses or amounts are inferred.
create table public.assiny_webhook_routes (
  connection_id uuid primary key references public.integration_connections(id) on delete cascade,
  token_fingerprint bytea not null unique,
  rotated_at timestamptz not null default now()
);
alter table public.assiny_webhook_routes enable row level security;
revoke all on public.assiny_webhook_routes from public, anon, authenticated;
grant all on public.assiny_webhook_routes to service_role;

create table public.assiny_webhook_receipts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  connection_id uuid not null,
  idempotency_key text not null check (idempotency_key ~ '^[a-f0-9]{64}$'),
  state text not null default 'awaiting_contract' check (state = 'awaiting_contract'),
  payload jsonb not null check (jsonb_typeof(payload) = 'object' and octet_length(payload::text) <= 1000000),
  received_at timestamptz not null default now(),
  unique (connection_id, idempotency_key),
  foreign key (organization_id, connection_id) references public.integration_connections(organization_id,id) on delete cascade
);
create index assiny_receipts_connection_received_idx on public.assiny_webhook_receipts (connection_id, received_at desc, id desc);
create index assiny_receipts_organization_idx on public.assiny_webhook_receipts (organization_id);
alter table public.assiny_webhook_receipts enable row level security;
create policy assiny_receipts_admin_read on public.assiny_webhook_receipts for select to authenticated
using (public.is_org_admin(organization_id));
revoke all on public.assiny_webhook_receipts from public, anon, authenticated;
grant select on public.assiny_webhook_receipts to authenticated;
grant all on public.assiny_webhook_receipts to service_role;

create function public.sync_assiny_webhook_route()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_connection_id uuid; v_secret jsonb; v_token text;
begin
  v_connection_id := case when tg_op = 'DELETE' then old.connection_id else new.connection_id end;
  if tg_op = 'DELETE' then
    delete from public.assiny_webhook_routes where connection_id = v_connection_id;
    return old;
  end if;
  perform 1 from public.integration_connections where id = v_connection_id and provider = 'assiny' for update;
  if not found then return new; end if;
  select decrypted_secret::jsonb into v_secret from vault.decrypted_secrets where id = new.vault_secret_id;
  v_token := v_secret ->> 'webhookToken';
  if v_secret ->> 'provider' is distinct from 'assiny' or v_secret ->> 'version' is distinct from '1'
    or v_token is null or v_token !~ '^[a-f0-9]{64}$' then raise exception 'invalid Assiny preparation token'; end if;
  insert into public.assiny_webhook_routes (connection_id,token_fingerprint,rotated_at)
  values (v_connection_id,extensions.digest(v_token,'sha256'),now())
  on conflict (connection_id) do update set token_fingerprint = excluded.token_fingerprint,rotated_at = excluded.rotated_at;
  update public.integration_connections set status = 'attention', last_verified_at = null,
    metadata = metadata - 'assiny_last_received_at' where id = v_connection_id;
  return new;
end;
$$;
revoke all on function public.sync_assiny_webhook_route() from public,anon,authenticated,service_role;
create trigger integration_secrets_sync_assiny after insert or update or delete on public.integration_secrets
for each row execute function public.sync_assiny_webhook_route();

-- These internal service-only routines are exposed for the Edge Function's RPC,
-- not for browser clients. The indexed token is generated by Genesis, not Assiny.
create function public.resolve_assiny_webhook_connection(p_connection_id uuid,p_token text)
returns uuid language sql stable security definer set search_path = '' as $$
  select route.connection_id from public.assiny_webhook_routes route
  join public.integration_connections connection on connection.id = route.connection_id
  where route.connection_id = p_connection_id and p_token ~ '^[a-f0-9]{64}$'
    and route.token_fingerprint = extensions.digest(p_token,'sha256')
    and connection.provider = 'assiny' and connection.revoked_at is null;
$$;
revoke all on function public.resolve_assiny_webhook_connection(uuid,text) from public,anon,authenticated;
grant execute on function public.resolve_assiny_webhook_connection(uuid,text) to service_role;

create function public.receive_assiny_webhook(p_connection_id uuid,p_token text,p_idempotency_key text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_connection public.integration_connections%rowtype; v_id uuid; v_duplicate boolean;
begin
  select * into v_connection from public.integration_connections where id = p_connection_id and provider = 'assiny' and revoked_at is null for update;
  if not found or public.resolve_assiny_webhook_connection(p_connection_id,p_token) is null then
    raise exception 'active authenticated Assiny connection required';
  end if;
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' or p_payload = '{}'::jsonb
    or octet_length(p_payload::text) > 1000000 or p_idempotency_key is null or p_idempotency_key !~ '^[a-f0-9]{64}$' then
    raise exception 'invalid Assiny preparation receipt';
  end if;
  insert into public.assiny_webhook_receipts (organization_id,connection_id,idempotency_key,payload)
  values (v_connection.organization_id,p_connection_id,p_idempotency_key,p_payload)
  on conflict (connection_id,idempotency_key) do nothing returning id into v_id;
  v_duplicate := v_id is null;
  if v_duplicate then select id into v_id from public.assiny_webhook_receipts where connection_id = p_connection_id and idempotency_key = p_idempotency_key; end if;
  update public.integration_connections set status = 'attention',last_verified_at = null,
    metadata = metadata || jsonb_build_object('assiny_last_received_at',now()) where id = p_connection_id;
  return jsonb_build_object('receipt_id',v_id,'duplicate',v_duplicate,'state','awaiting_contract');
end;
$$;
revoke all on function public.receive_assiny_webhook(uuid,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.receive_assiny_webhook(uuid,text,text,jsonb) to service_role;

-- Extend common onboarding only. Payment contracts remain independent.
do $$
declare v_routine regprocedure; v_source text; v_updated text; v_count integer := 0;
begin
  for v_routine in select oid::regprocedure from pg_proc
    where pronamespace = 'public'::regnamespace and proname in ('create_project_product_unchecked','create_project_with_funnel')
  loop
    v_source := pg_get_functiondef(v_routine);
    v_updated := replace(v_source,'''hotmart'', ''eduzz'', ''kiwify'', ''hubla'', ''payt''','''hotmart'', ''eduzz'', ''kiwify'', ''hubla'', ''payt'', ''assiny''');
    v_updated := replace(v_updated,'connection.provider = ''payt'' and connection.status = ''attention''','connection.provider in (''payt'', ''assiny'') and connection.status = ''attention''');
    if v_updated = v_source or strpos(v_updated,'''assiny''') = 0 then raise exception 'Assiny onboarding preflight failed for %',v_routine; end if;
    execute v_updated;
    v_count := v_count + 1;
  end loop;
  if v_count <> 2 then raise exception 'Assiny onboarding routines missing'; end if;
end;
$$;
